# Generated by Django 6.0 on 2026-02-02 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_propertyimage_image_url_propertyimage_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='selleravailability',
            options={'ordering': ['seller', 'start_time']},
        ),
        migrations.AlterUniqueTogether(
            name='selleravailability',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='selleravailability',
            name='days_of_week',
            field=models.JSONField(default=list),
        ),
        migrations.RemoveField(
            model_name='selleravailability',
            name='day_of_week',
        ),
    ]
