# Generated by Django 6.0 on 2026-04-02 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_selleravailability_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='location_text',
            field=models.CharField(blank=True, help_text='Human-readable city/location name like Lahore, Karachi etc.', max_length=100, null=True),
        ),
    ]
