# Generated by Django 6.0 on 2026-04-02 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_property_location_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commercial',
            old_name='washrooms',
            new_name='bathrooms',
        ),
    ]
